/* The documentation's screenshots, taken from the app itself.
 *
 *   node scripts/shoot-docs.mjs
 *
 * WHY THIS IS A SCRIPT AND NOT A FOLDER OF PNGs SOMEBODY ONCE MADE. A picture of a screen is a claim about
 * that screen, and a claim nobody can re-check is one that quietly stops being true: the button moves, the
 * sentence is reworded, and the document goes on showing last month's product with more confidence than the
 * text beside it. Twenty-six of them cannot be kept honest by hand. So they are regenerated by running this.
 *
 * THREE THINGS IT DOES THAT ARE NOT OBVIOUS, each of which cost an hour to find:
 *
 *   The dev server is served over HTTPS under the DEPLOYMENT'S OWN HOSTNAME, resolved to loopback by
 *   Chrome. Without it every picture of the app shows `http://localhost:4400/api/mcp` as the address to
 *   paste into Claude, which is worse than no picture. A self-signed certificate is generated here and
 *   trusted only by the browser this script launches.
 *
 *   It chdir()s into web/ before starting Vite. Tailwind's `content` globs are relative to the working
 *   directory, so from anywhere else it compiles a stylesheet with no utilities in it and every screenshot
 *   comes out as unstyled HTML — which looks like a broken app rather than a broken script.
 *
 *   Nothing is captured with a CLIP. Chrome reflows the page to the clip's size, so a 1400x920 "crop" of a
 *   1400-wide layout came back as a 2800-wide one with the sidebar collapsed and the columns rearranged.
 *   A region is captured by making the VIEWPORT that region instead.
 *
 * TWO PICTURES ARE STAGED, and both say so where they appear: the "Claude asked to start a recording here"
 * banner, and Connections before a machine is attached. Both need a computer that is NOT already attached to
 * an account, and any machine these are taken on is. Only two answers are stubbed for those - the agent's
 * /health and /api/mcp?pending=1 - and everything else on the page is the real component with real data.
 *
 * The consent page is rendered from `consentPage()` in api/oauth.js, the same function the server sends,
 * because a picture of a consent screen that is not the consent screen is the one picture nobody should
 * draw.
 *
 * Needs: Google Chrome, and `sips` (macOS) for the downscale at the end. The account data is the dev
 * fixture (MOCK_API=1); nothing here touches a real account or a real agent.
 */
import { spawn } from 'node:child_process';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const HOST = 'mouseflowapp.vercel.app';
const PORT = 4443;
const SITE = `https://${HOST}`;
const WIDTH = 1400;
const HEIGHT = 920;
const SCALE = 2;
/** What the PNGs are downscaled to. 1400 is the CSS width, so a retina capture lands back at 1x. */
const FINAL_WIDTH = 1400;

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const WEB = join(ROOT, 'web');
const OUT = join(ROOT, 'docs', 'img');
const work = mkdtempSync(join(tmpdir(), 'mf-docs-'));

const wait = (ms) => new Promise((r) => setTimeout(r, ms));

/* ------------------------------------------------------------------ the server */

function certificate() {
  const key = join(work, 'key.pem');
  const cert = join(work, 'cert.pem');
  execFileSync('openssl', [
    'req', '-x509', '-newkey', 'rsa:2048', '-nodes',
    '-keyout', key, '-out', cert, '-days', '2',
    '-subj', `/CN=${HOST}`,
    '-addext', `subjectAltName=DNS:${HOST},DNS:localhost`,
  ], { stdio: 'ignore' });
  return { key, cert };
}

async function serve() {
  const { key, cert } = certificate();
  process.env.MOCK_API = '1';
  // See the header: Tailwind resolves its content globs against the working directory.
  process.chdir(WEB);
  const { createServer } = await import(join(WEB, 'node_modules/vite/dist/node/index.js'));
  const server = await createServer({
    root: WEB,
    configFile: join(WEB, 'vite.config.ts'),
    logLevel: 'warn',
    server: {
      host: '127.0.0.1',
      port: PORT,
      strictPort: true,
      https: { key: readFileSync(key), cert: readFileSync(cert) },
    },
  });
  await server.listen();
  return server;
}

/* ------------------------------------------------------------------ the browser */

async function browser({ port = 9400, before = '' } = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'mf-chrome-'));
  const child = spawn(CHROME, [
    '--headless=new',
    `--remote-debugging-port=${port}`,
    `--user-data-dir=${dir}`,
    `--window-size=${WIDTH},${HEIGHT}`,
    `--force-device-scale-factor=${SCALE}`,
    '--hide-scrollbars', '--no-first-run', '--no-default-browser-check',
    '--disable-extensions', '--disable-gpu',
    `--host-resolver-rules=MAP ${HOST} 127.0.0.1:${PORT}`,
    '--ignore-certificate-errors',
    'about:blank',
  ], { stdio: 'ignore' });

  let up = null;
  for (let i = 0; i < 120 && !up; i++) {
    try {
      const res = await fetch(`http://127.0.0.1:${port}/json/version`);
      if (res.ok) up = await res.json();
    } catch (_) { /* not listening yet */ }
    if (!up) await wait(150);
  }
  if (!up) { child.kill(); throw new Error('Chrome never opened its debugging port'); }

  const targets = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  const target = targets.find((t) => t.type === 'page');
  const ws = new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((ok, no) => { ws.onopen = ok; ws.onerror = no; });

  let next = 1;
  const pending = new Map();
  const waiters = [];
  ws.onmessage = (ev) => {
    const msg = JSON.parse(ev.data);
    if (msg.id && pending.has(msg.id)) {
      const { ok, no } = pending.get(msg.id);
      pending.delete(msg.id);
      if (msg.error) no(new Error(msg.error.message)); else ok(msg.result);
      return;
    }
    for (let i = waiters.length - 1; i >= 0; i--) {
      if (waiters[i].method === msg.method) { waiters[i].ok(msg.params); waiters.splice(i, 1); }
    }
  };
  const send = (method, params = {}) => new Promise((ok, no) => {
    const id = next++;
    pending.set(id, { ok, no });
    ws.send(JSON.stringify({ id, method, params }));
  });
  const once = (method, ms = 20000) => new Promise((ok, no) => {
    const w = { method, ok };
    waiters.push(w);
    setTimeout(() => {
      const i = waiters.indexOf(w);
      if (i >= 0) { waiters.splice(i, 1); no(new Error('timed out waiting for ' + method)); }
    }, ms);
  });

  await send('Page.enable');
  await send('Runtime.enable');
  await send('Emulation.setDeviceMetricsOverride',
    { width: WIDTH, height: HEIGHT, deviceScaleFactor: SCALE, mobile: false });
  await send('Page.addScriptToEvaluateOnNewDocument', { source: HELPERS + before });

  const page = {
    async goto(url, settle = 1500) {
      const load = once('Page.loadEventFired').catch(() => {});
      await send('Page.navigate', { url });
      await load;
      await wait(settle);
    },
    async eval(expression) {
      const r = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true });
      if (r.exceptionDetails) throw new Error(r.exceptionDetails.text);
      return r.result.value;
    },
    /** Wait for something on the page rather than for a number of milliseconds. */
    async until(expression, tries = 40, every = 500) {
      for (let i = 0; i < tries; i++) {
        if (await page.eval(expression)) return true;
        await wait(every);
      }
      return false;
    },
    async shot(name) {
      const { data } = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false });
      writeFileSync(join(OUT, name), Buffer.from(data, 'base64'));
      console.log('  ' + name);
    },
    /* One element, by making the viewport its height. `pad` is also the gap left above it, which has to
     * clear the app's sticky header or the first line of whatever is being shown sits behind it. */
    async shotElement(name, selector, pad = 90) {
      const box = async () => page.eval(`(() => { const el = document.querySelector(${JSON.stringify(selector)});
        if (!el) return null; const r = el.getBoundingClientRect();
        return { y: r.y + scrollY, height: r.height }; })()`);
      let where = await box();
      if (!where) throw new Error('no element matching ' + selector);
      const tall = Math.min(4200, Math.ceil(where.height + pad * 2));
      await send('Emulation.setDeviceMetricsOverride',
        { width: WIDTH, height: tall, deviceScaleFactor: SCALE, mobile: false });
      await wait(400);
      where = await box();
      await page.eval(`scrollTo(0, ${Math.max(0, Math.round(where.y - pad))})`);
      await wait(400);
      await page.shot(name);
      await send('Emulation.setDeviceMetricsOverride',
        { width: WIDTH, height: HEIGHT, deviceScaleFactor: SCALE, mobile: false });
      await wait(250);
    },
    close() { try { ws.close(); } catch (_) { /* already gone */ } child.kill(); },
  };
  return page;
}

/** Clicking by what a person would read, rather than by a class somebody will rename. */
const HELPERS = `
window.__mf = {
  byText(text, selector) {
    const els = [...document.querySelectorAll(selector || 'button, a, [role="tab"]')];
    return els.find((e) => (e.textContent || '').trim().toLowerCase().includes(String(text).toLowerCase()));
  },
  clickText(text, selector) { const el = window.__mf.byText(text, selector); if (!el) return false; el.click(); return true; },
  clickExact(text) {
    const el = [...document.querySelectorAll('button')].find((b) => (b.textContent || '').trim() === text);
    if (!el) return false; el.click(); return true;
  },
  clickAttr(attr, value) {
    const el = document.querySelector('[' + attr + '^="' + value + '"]');
    if (!el) return false; el.click(); return true;
  },
  mark(text, selector, name) {
    const all = [...document.querySelectorAll(selector || 'div')].filter((d) => (d.textContent || '').includes(text));
    const el = all[all.length - 1];
    const box = el && (el.closest('.rounded-xl') || el);
    if (!box) return false;
    box.setAttribute('data-shot', name);
    return true;
  },
};
try { localStorage.setItem('mouseflow.theme', 'dark'); } catch (e) {}
`;

/* An agent that is attached to no account, and one queued request. The two answers that cannot be true on
 * a machine that is already attached — see the header. */
const STAGED = `
const HEALTH = {
  ok: true, version: '0.8.2', platform: 'macos', screen: { w: 1512, h: 982 },
  recording: false, playing: false, canSee: true, canWindows: true, canName: true,
  canKeys: true, canDrain: true, linked: false, autostart: true, canAutostart: true,
  permissions: { accessibility: true, screenRecording: true },
};
const real = window.fetch;
window.fetch = (input, init) => {
  const url = typeof input === 'string' ? input : (input && input.url) || '';
  if (/127\\.0\\.0\\.1:\\d+\\/health/.test(url)) {
    return Promise.resolve(new Response(JSON.stringify(HEALTH),
      { status: 200, headers: { 'content-type': 'application/json' } }));
  }
  if (url.indexOf('/api/mcp?pending=1') === 0) {
    return Promise.resolve(new Response(JSON.stringify({
      ok: true, waiting: 1, oldest: new Date().toISOString(), tools: ['mouseflow_start_recording'],
    }), { status: 200, headers: { 'content-type': 'application/json' } }));
  }
  return real(input, init);
};
`;

/* ------------------------------------------------------------------ the pictures */

async function openSettings(page, screen) {
  await page.goto(SITE + '/record', 2000);
  if (!await page.eval("window.__mf.clickAttr('title', 'Your account, connections')")) {
    throw new Error('the account button was not there');
  }
  await wait(700);
  if (!await page.eval(`window.__mf.clickExact(${JSON.stringify(screen)})`)) {
    throw new Error('no settings screen called ' + screen);
  }
  await wait(1200);
}

async function main() {
  if (!existsSync(CHROME)) throw new Error('This needs Google Chrome at ' + CHROME);
  mkdirSync(OUT, { recursive: true });

  console.log('starting the dev server…');
  const server = await serve();
  const taken = [];

  try {
    const page = await browser({ port: 9400 });
    try {
      /* A cold Vite transforms the whole module graph on the first request, and the first screenshot was
       * otherwise taken of a page that had not arrived. */
      console.log('warming…');
      for (const path of ['/record', '/mcp', '/skills', '/create', '/gallery', '/dashboard', '/connect']) {
        await page.goto(SITE + path, 2500);
      }

      console.log('taking:');
      await page.goto(SITE + '/mcp', 2500);
      await page.shot('mcp-page.png');
      for (const id of ['tools', 'connect', 'identity', 'doing', 'limits']) {
        await page.shotElement(`mcp-${id}.png`, '#' + id, 18);
      }

      await page.goto(SITE + '/record', 2500);
      await page.shot('record.png');
      await page.eval("window.__mf.clickText('View')");
      await wait(2000);
      await page.shot('record-transcript.png');

      await page.goto(SITE + '/record', 2500);
      await page.eval("window.__mf.clickAttr('aria-label', 'Make a skill from')");
      await wait(1600);
      await page.shot('record-skill-wizard.png');
      await page.eval("window.__mf.clickExact('Next')");
      await wait(1200);
      await page.shot('record-skill-wizard-2.png');

      await page.goto(SITE + '/skills', 2500);
      await page.shot('skills.png');
      await page.eval("window.__mf.clickAttr('aria-label', 'More for')");
      await wait(1000);
      // The structure fold is a <details>; opening it is what puts the tool definition on screen.
      await page.eval("document.querySelectorAll('details').forEach((d) => { d.open = true; })");
      await wait(400);
      await page.eval("window.__mf.clickExact('MCP')");
      await wait(800);
      await page.eval("document.querySelector('pre').scrollIntoView({ block: 'center' })");
      await wait(500);
      await page.shot('skills-structure.png');

      for (const [path, name] of [['/create', 'create'], ['/gallery', 'gallery'], ['/dashboard', 'dashboard']]) {
        await page.goto(SITE + path, 2500);
        await page.shot(name + '.png');
      }

      await page.goto(SITE + '/connect', 3000);
      await page.shot('connect-guide.png');
      if (await page.eval("window.__mf.mark('Connect an AI', 'section', 'ai')")) {
        await page.shotElement('connect-guide-ai.png', '[data-shot="ai"]', 90);
      }

      await openSettings(page, 'My account');
      await page.shot('settings-account.png');
      await page.eval("window.__mf.clickText('Pair a device')");
      await wait(1400);
      await page.shot('settings-account-token.png');

      await openSettings(page, 'Connections');
      await page.shot('settings-connections.png');
      await page.eval(`(() => {
        const row = [...document.querySelectorAll('[role="dialog"] div')]
          .find((d) => (d.textContent || '').startsWith('Connect an AI'));
        if (row) row.scrollIntoView({ block: 'center' });
        return !!row;
      })()`);
      await wait(700);
      await page.shot('settings-connections-mcp.png');

      await openSettings(page, 'Teams');
      await page.shot('settings-team.png');

      await openSettings(page, 'Hours');
      await page.shot('settings-hours.png');
    } finally {
      page.close();
    }

    /* The two staged ones, in a browser of their own so the stub cannot leak into anything above. */
    const staged = await browser({ port: 9401, before: STAGED });
    try {
      await staged.goto(SITE + '/record', 3000);
      const there = await staged.until(
        "window.__mf.mark('Claude asked to', 'div', 'banner')");
      if (!there) throw new Error('the banner never appeared');
      await wait(600);
      await staged.shotElement('record-waiting.png', '[data-shot="banner"]', 90);

      await openSettings(staged, 'Connections');
      await staged.eval(`(() => {
        const row = [...document.querySelectorAll('[role="dialog"] div')]
          .find((d) => (d.textContent || '').startsWith('Let Claude drive this computer'));
        if (row) row.scrollIntoView({ block: 'center' });
        return !!row;
      })()`);
      await wait(700);
      await staged.shot('settings-connections-attach.png');
    } finally {
      staged.close();
    }

    /* Signed out, last: the fixture's sign-out is global to the dev server. */
    const out = await browser({ port: 9402 });
    try {
      await out.goto(SITE + '/record', 2500);
      await out.eval("fetch('/api/auth/sign-out', { method: 'POST' })");
      await wait(900);
      await out.goto(SITE + '/sign-in', 2500);
      await out.shot('sign-in.png');
      await out.eval("fetch('/api/auth/sign-in', { method: 'POST' })");
    } finally {
      out.close();
    }

    /* The consent page, from the function the server sends rather than from a mock-up. */
    const { consentPage } = await import(join(ROOT, 'api', 'oauth.js'));
    const html = join(work, 'consent.html');
    writeFileSync(html, consentPage({
      origin: SITE,
      client: { id: 'mfc_2f1a9c0e7b34', name: 'Claude' },
      who: { email: 'vic@example.dev', name: 'Vic Gorlenko' },
      params: {
        client_id: 'mfc_2f1a9c0e7b34',
        redirect_uri: 'https://claude.ai/api/mcp/auth_callback',
        state: 'Xk92mB',
        code_challenge: 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM',
        code_challenge_method: 'S256',
        scope: 'mcp',
      },
    }));
    const consent = await browser({ port: 9403 });
    try {
      await consent.goto('file://' + html, 1200);
      await consent.shot('oauth-consent.png');
    } finally {
      consent.close();
    }
  } finally {
    await server.close();
  }

  /* Down to 1x. A retina capture is four times the bytes for a picture a document renders at container
   * width anyway, and this repository does not need eleven megabytes of PNG. */
  for (const file of readdirSync(OUT).filter((f) => f.endsWith('.png'))) {
    execFileSync('sips', ['--resampleWidth', String(FINAL_WIDTH), join(OUT, file), '--out', join(OUT, file)],
      { stdio: 'ignore' });
    taken.push(file);
  }
  console.log(`\n${taken.length} pictures in docs/img. Check them before committing - a screenshot is a `
    + 'claim, and this script cannot tell a rendered page from a rendered error.');
}

await main();
process.exit(0);
